Use AutoloadNamespaces instead of composer autoloader
I had tests failling such as:

1) NSFileRepo\Tests\NamespaceListTest::testGetReadableNoTalks
Error: Class 'NSFileRepo\Config' not found
2) NSFileRepo\Tests\NamespaceListTest::testGetReadableNoUnreadables
Error: Class 'NSFileRepo\Config' not found

Change-Id: Ic8828c0a83c388e51cc23259da60f7beae1a9567